server:
  port: 8080

spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf8
    hikari:
      max-lifetime: 6000000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none #update #create #validate
    show-sql: false #true #
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
    drop-first: true #false #

connection:
  userAgent: "Mozilla/5.0 (Windows; U; WindowsNT 5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6"
  referUrl: "http://www.google.com"

indexing-settings:
  sites:
    - url: https://dnd.su/race/
      name: Онлайн-справочник D&D 5 || Расы
#    - url: https://dnd.su/feats/
#      name: Онлайн-справочник D&D 5 || Черты
#    - url: https://dnd.fandom.com/ru/wiki/
#      name: Планарная энциклопедия
#    - url: https://ipfran.ru/
#      name: Институт прикладной физики им. А.В. Гапонова-Грехова Российской академии наук

