server:
  port: 8080

spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf8
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: false #true

indexing-settings:
  sites:
    - url: https://dnd.su/
      name: dnd.su
#    - url: https://www.playback.ru/
#      name: PlayBack.Ru
#    - url: https://ipfran.ru/
#      name: Институт прикладной физики им. А.В. Гапонова-Грехова Российской академии наук

